// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const knight_couch_1 = { y: 68, url, w: 28, h: 19, x: 0, };
export const knight_2_ride_1 = { y: 87, url, w: 28, h: 19, x: 0, };
export const footman_walk_1 = { y: 48, url, w: 10, h: 18, x: 24, };
export const footman_hit = { y: 56, url, w: 10, h: 10, x: 44, };
export const tile_rail = { y: 28, url, w: 16, h: 16, x: 32, };
export const tile_crowd = { y: 28, url, w: 16, h: 16, x: 48, };
export const tile_dirt = { y: 28, url, w: 16, h: 18, x: 0, };
export const knight_2_hit = { y: 87, url, w: 14, h: 16, x: 56, };
export const footman_walk_2 = { y: 48, url, w: 10, h: 18, x: 34, };
export const knight_couch_2 = { y: 68, url, w: 28, h: 19, x: 28, };
export const tile_wood = { y: 28, url, w: 16, h: 16, x: 16, };
export const knight_ride_1 = { y: 68, url, w: 25, h: 19, x: 56, };
export const knight_ride_2 = { y: 68, url, w: 25, h: 19, x: 81, };
export const the_king_walk_1 = { y: 48, url, w: 12, h: 20, x: 0, };
export const the_king_walk_2 = { y: 48, url, w: 12, h: 20, x: 12, };
export const knight_2_ride_2 = { y: 87, url, w: 28, h: 19, x: 28, };
export const font = { y: 0, url, w: 160, h: 28, x: 0, };
export const bearer_walk_1 = { y: 47, url, w: 9, h: 19, x: 54, };
export const bearer_walk_2 = { y: 47, url, w: 9, h: 19, x: 63, };