// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const knight_1 = { w: 25, x: 0, url, y: 0, h: 16, };
export const knight_2 = { w: 25, x: 90, url, y: 16, h: 16, };
export const villager_1_walk_1 = { w: 10, x: 0, url, y: 16, h: 18, };
export const villager_1_hit = { w: 9, x: 10, url, y: 21, h: 13, };
export const tile_rail = { w: 16, x: 64, url, y: 0, h: 16, };
export const tile_crowd = { w: 16, x: 80, url, y: 0, h: 16, };
export const tile_dirt = { w: 16, x: 96, url, y: 0, h: 16, };
export const villager_2 = { w: 11, x: 19, url, y: 20, h: 14, };
export const villager_2_hit = { w: 10, x: 30, url, y: 22, h: 12, };
export const knight_2_hit = { w: 14, x: 50, url, y: 0, h: 16, };
export const the_king = { w: 19, x: 71, url, y: 16, h: 21, };
export const villager_1_walk_2 = { w: 10, x: 0, url, y: 34, h: 18, };
export const knight_ride_2 = { w: 25, x: 25, url, y: 0, h: 16, };
export const tile_wood = { w: 16, x: 112, url, y: 0, h: 16, };
export const tile_flags = { w: 16, x: 128, url, y: 0, h: 16, };