// Generated by 'Export TypeScript Sprites' Aseprite Extension
import url from "./sprites.png"
export const knight_couch_1 = { w: 25, x: 0, url, y: 56, h: 19, };
export const knight_2_ride_1 = { w: 25, x: 0, url, y: 75, h: 16, };
export const villager_1_walk_1 = { w: 10, x: 0, url, y: 16, h: 18, };
export const villager_1_hit = { w: 10, x: 20, url, y: 24, h: 10, };
export const tile_rail = { w: 16, x: 16, url, y: 0, h: 16, };
export const tile_crowd = { w: 16, x: 48, url, y: 0, h: 16, };
export const tile_dirt = { w: 16, x: 0, url, y: 0, h: 16, };
export const knight_2_hit = { w: 14, x: 50, url, y: 75, h: 16, };
export const villager_1_walk_2 = { w: 10, x: 10, url, y: 16, h: 18, };
export const knight_couch_2 = { w: 25, x: 25, url, y: 56, h: 19, };
export const tile_wood = { w: 16, x: 32, url, y: 0, h: 16, };
export const tile_flags = { w: 16, x: 64, url, y: 0, h: 16, };
export const knight_ride_1 = { w: 25, x: 50, url, y: 56, h: 19, };
export const knight_ride_2 = { w: 25, x: 75, url, y: 56, h: 19, };
export const the_king_walk_1 = { w: 12, x: 0, url, y: 34, h: 20, };
export const the_king_walk_2 = { w: 12, x: 12, url, y: 34, h: 20, };
export const knight_2_ride_2 = { w: 25, x: 25, url, y: 75, h: 16, };